### ISSUE TITLE
Check 62 roadmap

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#407]
List of features to be added in CHECK_62
- [ ] https://github.com/larshp/abapOpenChecks/issues/66 LOOPs that can be reduced with WHERE
- [ ] https://github.com/larshp/abapOpenChecks/issues/379 checking for table lines before looping
- [ ] https://github.com/larshp/abapOpenChecks/issues/376 LOOP AT can be replaced with READ TABLE
